name: Scheduler Workflow

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta todos los días a las 23:59 (UTC)
    - cron: '*/15 * * * *'  
  # Permite ejecutar manualmente desde Actions

jobs:
  invoke-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: validate execution
        run: |
          echo "Ejecutando workflow programado"
          echo "Fecha/hora del runner (local): $(date '+%Y-%m-%d %H:%M:%S %Z')"
          echo "Fecha/hora UTC: $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
  call-another-workflow:
    needs: invoke-workflow
    uses: ./.github/workflows/another-workflow.yml
